name: Mon premier Workflow

on: push

jobs:
    premier_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6
        
        - name: Message de bienvenue
          run: |
            echo "Mon premier GitHub Action Job"
            ls -ltra
            cat README.md
        - name: Genere ASCIi Artwork
          run: cowsay -f dragon "Bonjour, Je suis le DRAGON" >> dragon.txt

    #    - name: List files
    #      run: ls

    #    - name: Read file
    #      run: cat README.md